// Generated by the translation pipeline. Only fully translated categories are listed.
import type { Locale } from "@/i18n/config";
import type { ToolTextDictionary } from "@/i18n/tool-text";
import type { ToolPageTranslations } from "./types";
import common_ptbr from "./common/pt-br";
import common_nl from "./common/nl";
import common_ar from "./common/ar";
import common_es from "./common/es";
import common_fr from "./common/fr";
import common_id from "./common/id";
import common_de from "./common/de";
import common_it from "./common/it";
import common_tr from "./common/tr";
import common_ru from "./common/ru";
import common_hi from "./common/hi";
import common_ur from "./common/ur";
import common_ja from "./common/ja";
import common_ko from "./common/ko";
import texttools_ptbr from "./text-tools/pt-br";
import texttools_nl from "./text-tools/nl";
import texttools_ar from "./text-tools/ar";
import texttools_es from "./text-tools/es";
import texttools_fr from "./text-tools/fr";
import texttools_id from "./text-tools/id";
import texttools_de from "./text-tools/de";
import texttools_it from "./text-tools/it";
import texttools_tr from "./text-tools/tr";
import texttools_ru from "./text-tools/ru";
import texttools_hi from "./text-tools/hi";
import texttools_ur from "./text-tools/ur";
import texttools_ja from "./text-tools/ja";
import texttools_ko from "./text-tools/ko";
import aitools_ptbr from "./ai-tools/pt-br";
import aitools_nl from "./ai-tools/nl";
import aitools_ar from "./ai-tools/ar";
import aitools_es from "./ai-tools/es";
import aitools_fr from "./ai-tools/fr";
import aitools_id from "./ai-tools/id";
import aitools_de from "./ai-tools/de";
import aitools_it from "./ai-tools/it";
import aitools_tr from "./ai-tools/tr";
import aitools_ru from "./ai-tools/ru";
import aitools_hi from "./ai-tools/hi";
import aitools_ur from "./ai-tools/ur";
import aitools_ja from "./ai-tools/ja";
import aitools_ko from "./ai-tools/ko";

export const commonToolText: Partial<Record<Locale, ToolTextDictionary>> = {
  "pt-br": common_ptbr,
  "nl": common_nl,
  "ar": common_ar,
  "es": common_es,
  "fr": common_fr,
  "id": common_id,
  "de": common_de,
  "it": common_it,
  "tr": common_tr,
  "ru": common_ru,
  "hi": common_hi,
  "ur": common_ur,
  "ja": common_ja,
  "ko": common_ko,
};

export const toolPageTranslations: Partial<Record<Locale, ToolPageTranslations>> = {
  "pt-br": { ...texttools_ptbr, ...aitools_ptbr },
  "nl": { ...texttools_nl, ...aitools_nl },
  "ar": { ...texttools_ar, ...aitools_ar },
  "es": { ...texttools_es, ...aitools_es },
  "fr": { ...texttools_fr, ...aitools_fr },
  "id": { ...texttools_id, ...aitools_id },
  "de": { ...texttools_de, ...aitools_de },
  "it": { ...texttools_it, ...aitools_it },
  "tr": { ...texttools_tr, ...aitools_tr },
  "ru": { ...texttools_ru, ...aitools_ru },
  "hi": { ...texttools_hi, ...aitools_hi },
  "ur": { ...texttools_ur, ...aitools_ur },
  "ja": { ...texttools_ja, ...aitools_ja },
  "ko": { ...texttools_ko, ...aitools_ko },
};

/** Categories whose tool pages are translated in every language. */
export const translatedToolCategories: readonly string[] = ["text-tools", "ai-tools"];
